name: Build Docker Image

on:
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build image
      run: docker build . --file Dockerfile --tag puzzlepieces:${{ GITHUB_SHA }}
