uses: actions/ansible-playbook-docker-action@2.8.5
with:



  name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: checkout
      
    - name: Execute Deployment Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.2
      with:
        playbookName: 'ops/ansible/deploy.yml'
        inventoryFile: ''
        keyFile: ".ansible/random-ssh-key.pem"
        keyFileVaultPass: ${{ secrets.KEYFILE_VAULT_PASS }}
        extraFile: ".ansible/extra.yml"
        extraVars: "-e my_first_extra=${{ github.actor }} -e my_second_one=${{ github.sha }}"
        verbosity: "vv"