name: Deploy Development Instance

on:
  push:
    branches:
      - master
jobs:
    deploy:
      runs-on: ubuntu-latest
      name: deploy with ansible
      steps:
        - uses: actions/checkout@v1

        - name: setup ssh agent
          uses: webfactory/ssh-agent@v0.2.0
          with:
            ssh-private-key: ${{ secrets.DEV_DEPLOY_SSH_PRIVATEKEY }}
        
        - name: setup python
          uses: actions/setup-python@v1.1.1
          with:
            python-version: 3.8
        
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ansible==2.9.2 requests

        - name: run playbooks/configure
          run: |
            ansible-playbook ops/ansible/configure.yml \
              -i ${{ secrets.DEV_DEPLOY_URL }}, \
              -u ${{ secrets.DEV_DEPLOY_USER }}

        - name: run playbooks/deploy
          run: |
            ansible-playbook ops/ansible/configure.yml \
              -i ${{ secrets.DEV_INSTANCE_URL }}, \
              -u ${{ secrets.DEV_DEPLOY_USER }} \
              --extra-vars=${{ secrets.ANSIBLE_ENV_DEV }} \
              --extra-vars='{"gh":{"user":"corridors-of-time-transcription","pass":"${{ secrets.GITHUB_TOKEN }}"}'